// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdEF7yxJRyvLW4PZuH-YKPnr0UgXo4Na0',
    appId: '1:26056002141:web:ec4e4cd70a539b8c681bb4',
    messagingSenderId: '26056002141',
    projectId: 'labconnect-b02c4',
    authDomain: 'labconnect-b02c4.firebaseapp.com',
    storageBucket: 'labconnect-b02c4.firebasestorage.app',
    measurementId: 'G-0735DYL2EC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuM2e25RDSWhyrA-NBOU3GYZETLJFjFX4',
    appId: '1:26056002141:android:7477635751f9ab59681bb4',
    messagingSenderId: '26056002141',
    projectId: 'labconnect-b02c4',
    storageBucket: 'labconnect-b02c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrehcIKcIBXh5a5dlPF614CvG06r4lPNo',
    appId: '1:26056002141:ios:4734d28815c04392681bb4',
    messagingSenderId: '26056002141',
    projectId: 'labconnect-b02c4',
    storageBucket: 'labconnect-b02c4.firebasestorage.app',
    iosBundleId: 'com.monentreprise.connect.connectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrehcIKcIBXh5a5dlPF614CvG06r4lPNo',
    appId: '1:26056002141:ios:4734d28815c04392681bb4',
    messagingSenderId: '26056002141',
    projectId: 'labconnect-b02c4',
    storageBucket: 'labconnect-b02c4.firebasestorage.app',
    iosBundleId: 'com.monentreprise.connect.connectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdEF7yxJRyvLW4PZuH-YKPnr0UgXo4Na0',
    appId: '1:26056002141:web:1ab1cbcfc6158582681bb4',
    messagingSenderId: '26056002141',
    projectId: 'labconnect-b02c4',
    authDomain: 'labconnect-b02c4.firebaseapp.com',
    storageBucket: 'labconnect-b02c4.firebasestorage.app',
    measurementId: 'G-R9MLGW77S2',
  );
}
